import 'package:flutter/material.dart';

enum SettingScope {
  db,
  prefs,
  secure,
}

enum SettingType {
  boolean,
  integer,
  text,
  enumeration,
  time,
}

enum SettingsGroup {
  identity,
  modules,
  notifications,
  appearance,
  assistant,
  dataBackup,
  security,
}

@immutable
class SettingDescriptor {
  const SettingDescriptor({
    required this.key,
    required this.type,
    required this.scope,
    required this.defaultValue,
    required this.labelFa,
    required this.group,
    this.descriptionFa,
    this.min,
    this.max,
    this.allowed,
    this.aiWritable = false,
    this.searchTerms = const [],
  });

  final String key;
  final SettingType type;
  final SettingScope scope;
  final Object defaultValue;
  final String labelFa;
  final SettingsGroup group;
  final String? descriptionFa;
  final num? min;
  final num? max;
  final List<String>? allowed;
  final bool aiWritable;
  final List<String> searchTerms;
}

class SettingsRegistry {
  SettingsRegistry._();

  static const List<SettingDescriptor> all = [
    // ----------------------------------------------------
    // ۱. حساب و هویت (Identity)
    // ----------------------------------------------------
    SettingDescriptor(
      key: 'user_name',
      type: SettingType.text,
      scope: SettingScope.db,
      defaultValue: 'بهمن',
      labelFa: 'نام و نام خانوادگی',
      group: SettingsGroup.identity,
      descriptionFa: 'نام نمایش‌داده‌شده در سربرگ و گفتگوهای هوش مصنوعی',
      searchTerms: ['نام', 'اسم', 'پروفایل', 'هویت'],
    ),
    SettingDescriptor(
      key: 'user_gender',
      type: SettingType.enumeration,
      scope: SettingScope.db,
      defaultValue: 'UNSET',
      labelFa: 'جنسیت',
      group: SettingsGroup.identity,
      allowed: ['UNSET', 'male', 'female', 'other'],
      descriptionFa: 'برای تنظیم پیشنهادهای زیستی و سلامت',
      searchTerms: ['جنسیت', 'زن', 'مرد'],
    ),
    SettingDescriptor(
      key: 'user_age',
      type: SettingType.integer,
      scope: SettingScope.db,
      defaultValue: 25,
      labelFa: 'سن',
      group: SettingsGroup.identity,
      min: 10,
      max: 120,
      descriptionFa: 'محاسبه انرژی پایه و ظرفیت روزانه',
      searchTerms: ['سن', 'سال', 'تولد'],
    ),
    SettingDescriptor(
      key: 'user_avatar_path',
      type: SettingType.text,
      scope: SettingScope.db,
      defaultValue: '',
      labelFa: 'تصویر پروفایل',
      group: SettingsGroup.identity,
      descriptionFa: 'مسیر محلی عکس ذخیره‌شده',
      searchTerms: ['عکس', 'آواتار', 'پروفایل', 'تصویر'],
    ),
    SettingDescriptor(
      key: 'app_mode',
      type: SettingType.enumeration,
      scope: SettingScope.db,
      defaultValue: 'full',
      labelFa: 'حالت اپ (ساده / کامل)',
      group: SettingsGroup.identity,
      allowed: ['full', 'simple'],
      descriptionFa: 'حالت ساده فقط روتین‌ها و زمان‌سنج‌ها را نمایش می‌دهد',
      searchTerms: ['ساده', 'کامل', 'حالت', 'سبک'],
    ),
    SettingDescriptor(
      key: 'identity_gender_asked',
      type: SettingType.boolean,
      scope: SettingScope.db,
      defaultValue: false,
      labelFa: 'وضعیت پرسش جنسیت',
      group: SettingsGroup.identity,
    ),
    SettingDescriptor(
      key: 'identity_age_asked',
      type: SettingType.boolean,
      scope: SettingScope.db,
      defaultValue: false,
      labelFa: 'وضعیت پرسش سن',
      group: SettingsGroup.identity,
    ),
    SettingDescriptor(
      key: 'onboarding_completed',
      type: SettingType.boolean,
      scope: SettingScope.prefs,
      defaultValue: true,
      labelFa: 'تکمیل راه‌اندازی اولیه',
      group: SettingsGroup.identity,
    ),

    // ----------------------------------------------------
    // ۲. ماژول‌ها و بخش‌های برنامه (Modules)
    // ----------------------------------------------------
    SettingDescriptor(
      key: 'module_today_routines',
      type: SettingType.boolean,
      scope: SettingScope.db,
      defaultValue: true,
      labelFa: 'امروز و روتین‌ها',
      group: SettingsGroup.modules,
      descriptionFa: 'هستهٔ اصلی پیگیری عادت‌ها و فعالیت‌های روزانه',
      searchTerms: ['امروز', 'روتین', 'عادت'],
    ),
    SettingDescriptor(
      key: 'module_calendar_journey',
      type: SettingType.boolean,
      scope: SettingScope.db,
      defaultValue: true,
      labelFa: 'تقویم و سفر',
      group: SettingsGroup.modules,
      descriptionFa: 'نمای خط زمانی و برنامه‌ریزی ماهانه و هفتگی',
      searchTerms: ['تقویم', 'سفر', 'برنامه‌ریزی'],
    ),
    SettingDescriptor(
      key: 'module_assistant_enabled',
      type: SettingType.boolean,
      scope: SettingScope.db,
      defaultValue: true,
      labelFa: 'دستیار هوشمند',
      group: SettingsGroup.modules,
      descriptionFa: 'دستیار همراه و پیشنهادهای خودمراقبتی',
      searchTerms: ['دستیار', 'هوش مصنوعی', 'چت'],
    ),
    SettingDescriptor(
      key: 'module_goals_enabled',
      type: SettingType.boolean,
      scope: SettingScope.db,
      defaultValue: false,
      labelFa: 'اهداف و پیشرفت',
      group: SettingsGroup.modules,
      descriptionFa: 'تعریف اهداف کلیدی و شکستن آن‌ها به گام‌ها',
      searchTerms: ['هدف', 'اهداف', 'پیشرفت'],
    ),
    SettingDescriptor(
      key: 'module_study_enabled',
      type: SettingType.boolean,
      scope: SettingScope.db,
      defaultValue: false,
      labelFa: 'درس و مطالعه',
      group: SettingsGroup.modules,
      descriptionFa: 'برنامهٔ مطالعه، سرفصل‌ها و مرور جعبه لایتنر',
      searchTerms: ['درس', 'مطالعه', 'کنکور', 'امتحان'],
    ),
    SettingDescriptor(
      key: 'module_courses_enabled',
      type: SettingType.boolean,
      scope: SettingScope.db,
      defaultValue: false,
      labelFa: 'دوره‌های آموزشی',
      group: SettingsGroup.modules,
      descriptionFa: 'مدیریت جلسات و پیشرفت دوره‌های یادگیری',
      searchTerms: ['دوره', 'آموزش', 'کلاس'],
    ),
    SettingDescriptor(
      key: 'module_religion_enabled',
      type: SettingType.boolean,
      scope: SettingScope.db,
      defaultValue: false,
      labelFa: 'عبادت و معنویت',
      group: SettingsGroup.modules,
      descriptionFa: 'اذان، اوقات شرعی، ادعیه و نمازهای مستحبی',
      searchTerms: ['نماز', 'عبادت', 'معنویت', 'دعا', 'اذان'],
    ),
    SettingDescriptor(
      key: 'module_sports_enabled',
      type: SettingType.boolean,
      scope: SettingScope.db,
      defaultValue: false,
      labelFa: 'ورزش و تحرک',
      group: SettingsGroup.modules,
      descriptionFa: 'برنامه‌های تمرینی و فعالیت‌های بدنی',
      searchTerms: ['ورزش', 'تحرک', 'تمرین', 'بدنسازی'],
    ),
    SettingDescriptor(
      key: 'module_medicine_enabled',
      type: SettingType.boolean,
      scope: SettingScope.db,
      defaultValue: false,
      labelFa: 'دارو و سلامت',
      group: SettingsGroup.modules,
      descriptionFa: 'یادآوری مصرف داروها و پیگیری سلامتی',
      searchTerms: ['دارو', 'سلامت', 'پزشکی', 'قرص'],
    ),
    SettingDescriptor(
      key: 'module_sleep_enabled',
      type: SettingType.boolean,
      scope: SettingScope.db,
      defaultValue: false,
      labelFa: 'خواب و ریتم شبانه‌روزی',
      group: SettingsGroup.modules,
      descriptionFa: 'ثبت کیفیت خواب و همگام‌سازی ساعت زیستی',
      searchTerms: ['خواب', 'شب', 'ریتم زیستی', 'استراحت'],
    ),
    SettingDescriptor(
      key: 'module_cycle_enabled',
      type: SettingType.boolean,
      scope: SettingScope.db,
      defaultValue: false,
      labelFa: 'چرخهٔ زیستی',
      group: SettingsGroup.modules,
      descriptionFa: 'پیگیری حریم‌دار چرخهٔ بانوان',
      searchTerms: ['چرخه', 'بانوان', 'پریود', 'سلامت زنان'],
    ),
    SettingDescriptor(
      key: 'module_energy_enabled',
      type: SettingType.boolean,
      scope: SettingScope.db,
      defaultValue: false,
      labelFa: 'تحلیل انرژی',
      group: SettingsGroup.modules,
      descriptionFa: 'ارزیابی و تحلیل پنجره‌های انرژی در طول روز',
      searchTerms: ['انرژی', 'پالس', 'خستگی'],
    ),
    SettingDescriptor(
      key: 'module_progressive_habits_enabled',
      type: SettingType.boolean,
      scope: SettingScope.db,
      defaultValue: false,
      labelFa: 'عادت‌های پیش‌رونده',
      group: SettingsGroup.modules,
      descriptionFa: 'افزایش تدریجی و خودکار گام‌های روتین',
      searchTerms: ['عادت', 'گام', 'پیشرونده'],
    ),
    SettingDescriptor(
      key: 'module_supplementary_sports_enabled',
      type: SettingType.boolean,
      scope: SettingScope.db,
      defaultValue: false,
      labelFa: 'ورزش تکمیلی و کششی',
      group: SettingsGroup.modules,
      descriptionFa: 'تمرینات انعطاف‌پذیری و جانبی',
      searchTerms: ['ورزش', 'تکمیلی', 'کشش'],
    ),

    // ----------------------------------------------------
    // ۳. اعلان‌ها و یادآوری‌ها (Notifications)
    // ----------------------------------------------------
    SettingDescriptor(
      key: 'notif_master_enabled',
      type: SettingType.boolean,
      scope: SettingScope.db,
      defaultValue: true,
      labelFa: 'اعلان‌های سراسری',
      group: SettingsGroup.notifications,
      descriptionFa: 'فعال یا غیرفعال‌سازی همهٔ اعلان‌ها و یادآوری‌ها',
      aiWritable: true,
      searchTerms: ['اعلان', 'یادآوری', 'نوتیفیکیشن', 'پیام'],
    ),
    SettingDescriptor(
      key: 'notif_quiet_enabled',
      type: SettingType.boolean,
      scope: SettingScope.db,
      defaultValue: false,
      labelFa: 'ساعات سکوت',
      group: SettingsGroup.notifications,
      descriptionFa: 'قطع موقت اعلان‌های غیراضطراری در ساعات مشخص',
      aiWritable: true,
      searchTerms: ['سکوت', 'ساعت سکوت', 'شب', 'مزاحم نشوید'],
    ),
    SettingDescriptor(
      key: 'notif_quiet_start',
      type: SettingType.time,
      scope: SettingScope.db,
      defaultValue: '00:00',
      labelFa: 'شروع ساعات سکوت',
      group: SettingsGroup.notifications,
      descriptionFa: 'زمان آغاز عدم ارسال اعلان‌های غیراضطراری',
      searchTerms: ['شروع سکوت', 'زمان سکوت'],
    ),
    SettingDescriptor(
      key: 'notif_quiet_end',
      type: SettingType.time,
      scope: SettingScope.db,
      defaultValue: '07:00',
      labelFa: 'پایان ساعات سکوت',
      group: SettingsGroup.notifications,
      descriptionFa: 'زمان پایان سکوت و شروع مجدد اعلان‌ها',
      searchTerms: ['پایان سکوت', 'صبح'],
    ),
    SettingDescriptor(
      key: 'persistent_status_notification_enabled',
      type: SettingType.boolean,
      scope: SettingScope.db,
      defaultValue: true,
      labelFa: 'اعلان دائمی وضعیت',
      group: SettingsGroup.notifications,
      descriptionFa: 'نمایش ویجت زندهٔ وظیفه جاری در نوار اعلان‌ها',
      searchTerms: ['اعلان دائم', 'استاتوس', 'نوار وضعیت'],
    ),
    SettingDescriptor(
      key: 'digest_mode',
      type: SettingType.enumeration,
      scope: SettingScope.db,
      defaultValue: 'standard',
      labelFa: 'حالت خلاصه اعلان',
      group: SettingsGroup.notifications,
      allowed: ['standard', 'concise', 'grouped'],
      descriptionFa: 'نحوهٔ نمایش دسته‌ای پیام‌ها و یادآوری‌ها',
      searchTerms: ['خلاصه', 'دایجست', 'تجمیع پیام'],
    ),
    SettingDescriptor(
      key: 'coalescing_window_minutes',
      type: SettingType.integer,
      scope: SettingScope.db,
      defaultValue: 15,
      labelFa: 'بازهٔ تجمیع اعلان‌ها',
      group: SettingsGroup.notifications,
      min: 1,
      max: 60,
      descriptionFa: 'فاصله زمانی ادغام اعلان‌های نزدیک به هم (دقیقه)',
      searchTerms: ['تجمیع', 'دقیقه', 'پنجره'],
    ),
    SettingDescriptor(
      key: 'max_non_essential_per_hour',
      type: SettingType.integer,
      scope: SettingScope.db,
      defaultValue: 3,
      labelFa: 'سقف اعلان‌های غیراضطراری در ساعت',
      group: SettingsGroup.notifications,
      min: 1,
      max: 20,
      descriptionFa: 'حداکثر پیام‌های غیربحرانی در هر ۶۰ دقیقه',
      searchTerms: ['سقف اعلان', 'تعداد پیام', 'محدودیت'],
    ),
    SettingDescriptor(
      key: 'snooze_minutes',
      type: SettingType.integer,
      scope: SettingScope.db,
      defaultValue: 10,
      labelFa: 'زمان تعویق پیش‌فرض (دقیقه)',
      group: SettingsGroup.notifications,
      min: 1,
      max: 120,
      descriptionFa: 'فاصلهٔ زمانی تا یادآوری مجدد بعد از اسنوز',
      searchTerms: ['تعویق', 'اسنوز', 'یادآوری مجدد'],
    ),
    SettingDescriptor(
      key: 'snooze_max_defer_count',
      type: SettingType.integer,
      scope: SettingScope.db,
      defaultValue: 3,
      labelFa: 'حداکثر دفعات تعویق مجاز',
      group: SettingsGroup.notifications,
      min: 0,
      max: 10,
      descriptionFa: 'تعداد دفعات مجاز برای به تعویق انداختن یک روتین',
      searchTerms: ['حداکثر تعویق', 'دفعات اسنوز'],
    ),

    // ----------------------------------------------------
    // ۴. ظاهر و زبان (Appearance & Locale)
    // ----------------------------------------------------
    SettingDescriptor(
      key: 'theme_mode',
      type: SettingType.enumeration,
      scope: SettingScope.db,
      defaultValue: 'system',
      labelFa: 'حالت روشنایی تم',
      group: SettingsGroup.appearance,
      allowed: ['system', 'light', 'dark'],
      descriptionFa: 'تاریک، روشن یا هماهنگ با سیستم‌عامل',
      aiWritable: true,
      searchTerms: ['تم', 'تاریک', 'روشن', 'شب', 'روز'],
    ),
    SettingDescriptor(
      key: 'theme_palette',
      type: SettingType.enumeration,
      scope: SettingScope.db,
      defaultValue: 'ritmo',
      labelFa: 'پالت رنگی برنامه',
      group: SettingsGroup.appearance,
      allowed: ['ritmo', 'emerald', 'sunset', 'sapphire', 'amethyst', 'rose', 'nordic', 'amber'],
      descriptionFa: 'رنگ پایه و اتمسفر بصری محیط برنامه',
      searchTerms: ['پالت', 'رنگ', 'زمرد', 'یاقوت', 'طلایی'],
    ),
    SettingDescriptor(
      key: 'theme_reduce_transparency',
      type: SettingType.boolean,
      scope: SettingScope.db,
      defaultValue: false,
      labelFa: 'کاهش افکت شیشه‌ای',
      group: SettingsGroup.appearance,
      descriptionFa: 'افزایش کنتراست و حذف مات‌شدگی پس‌زمینه برای خوانایی بهتر',
      searchTerms: ['شفافیت', 'ماتی', 'بلور', 'کنتراست'],
    ),
    SettingDescriptor(
      key: 'theme_true_black',
      type: SettingType.boolean,
      scope: SettingScope.db,
      defaultValue: false,
      labelFa: 'سیاه خالص (OLED)',
      group: SettingsGroup.appearance,
      descriptionFa: 'استفاده از سیاه عمیق جهت صرفه‌جویی در باتری',
      searchTerms: ['سیاه', 'امولد', 'oled', 'تاریک خالص'],
    ),
    SettingDescriptor(
      key: 'locale',
      type: SettingType.enumeration,
      scope: SettingScope.db,
      defaultValue: 'fa',
      labelFa: 'زبان برنامه',
      group: SettingsGroup.appearance,
      allowed: ['fa', 'en'],
      descriptionFa: 'فارسی یا انگلیسی',
      searchTerms: ['زبان', 'فارسی', 'انگلیسی', 'locale'],
    ),

    // ----------------------------------------------------
    // ۵. دستیار و حریم خصوصی (Assistant & Privacy)
    // ----------------------------------------------------
    SettingDescriptor(
      key: 'ai_mode',
      type: SettingType.enumeration,
      scope: SettingScope.db,
      defaultValue: 'ritmo_server',
      labelFa: 'حالت اتصال هوش مصنوعی',
      group: SettingsGroup.assistant,
      allowed: ['ritmo_server', 'personal_key'],
      descriptionFa: 'استفاده از سرور امن ریتمو یا کلید شخصی کاربر',
      searchTerms: ['هوش مصنوعی', 'سرور', 'کلید شخصی', 'api'],
    ),
    SettingDescriptor(
      key: 'ai_provider_preset',
      type: SettingType.enumeration,
      scope: SettingScope.db,
      defaultValue: 'zhipu',
      labelFa: 'سرویس‌دهنده هوش مصنوعی',
      group: SettingsGroup.assistant,
      allowed: ['zhipu', 'openrouter', 'cloudflare', 'groq', 'local', 'custom'],
      descriptionFa: 'انتخاب ارائه‌دهنده مدل هوش مصنوعی',
      searchTerms: ['ارائه‌دهنده', 'ژیپو', 'کلودفلر', 'اوپن روتر'],
    ),
    SettingDescriptor(
      key: 'ai_base_url',
      type: SettingType.text,
      scope: SettingScope.db,
      defaultValue: '',
      labelFa: 'آدرس سرویس‌دهنده هوش مصنوعی',
      group: SettingsGroup.assistant,
      descriptionFa: 'Endpoint اختصاصی برای ارتباط چت',
      searchTerms: ['آدرس هوش مصنوعی', 'url', 'endpoint'],
    ),
    SettingDescriptor(
      key: 'ai_api_key',
      type: SettingType.text,
      scope: SettingScope.secure,
      defaultValue: '',
      labelFa: 'کلید دسترسی هوش مصنوعی',
      group: SettingsGroup.assistant,
      descriptionFa: 'ذخیره رمزنگاری‌شده در حافظه امن دستگاه',
      searchTerms: ['کلید api', 'api key', 'رمز هوش مصنوعی'],
    ),
    SettingDescriptor(
      key: 'ai_model',
      type: SettingType.text,
      scope: SettingScope.db,
      defaultValue: '',
      labelFa: 'نام مدل هوش مصنوعی',
      group: SettingsGroup.assistant,
      descriptionFa: 'شناسه مدل مورد استفاده برای پاسخگویی',
      searchTerms: ['مدل', 'model', 'glm', 'llama'],
    ),
    SettingDescriptor(
      key: 'ai_timeout',
      type: SettingType.integer,
      scope: SettingScope.db,
      defaultValue: 60000,
      labelFa: 'مهلت پاسخ هوش مصنوعی (میلی‌ثانیه)',
      group: SettingsGroup.assistant,
      min: 5000,
      max: 300000,
      descriptionFa: 'تایم‌اوت ارتباط شبکه با سرویس‌دهنده',
      searchTerms: ['تایم اوت', 'مهلت پاسخ', 'زمان اتصال'],
    ),
    SettingDescriptor(
      key: 'ai_memory_enabled',
      type: SettingType.boolean,
      scope: SettingScope.db,
      defaultValue: true,
      labelFa: 'حافظهٔ شناختی دستیار',
      group: SettingsGroup.assistant,
      descriptionFa: 'به خاطر سپردن ترجیحات و عادات کاربر',
      searchTerms: ['حافظه', 'شناختی', 'یادگیری'],
    ),
    SettingDescriptor(
      key: 'ai_memory_implicit_enabled',
      type: SettingType.boolean,
      scope: SettingScope.db,
      defaultValue: true,
      labelFa: 'یادگیری خودکار و ضمنی',
      group: SettingsGroup.assistant,
      descriptionFa: 'استخراج هوشمند الگوی روزمره بدون نیاز به ثبت دستی',
      searchTerms: ['یادگیری خودکار', 'ضمنی', 'عادات'],
    ),
    SettingDescriptor(
      key: 'assistant_cloud_consent',
      type: SettingType.boolean,
      scope: SettingScope.prefs,
      defaultValue: true,
      labelFa: 'رضایت‌نامه پردازش ابری',
      group: SettingsGroup.assistant,
      descriptionFa: 'مجوز ارسال خلاصه‌های متنی به سرویس هوش مصنوعی',
      searchTerms: ['رضایت', 'ابر', 'حریم خصوصی', 'امنیت داده'],
    ),
    SettingDescriptor(
      key: 'assistant_briefing_enabled',
      type: SettingType.boolean,
      scope: SettingScope.db,
      defaultValue: true,
      labelFa: 'خلاصه‌ساز روزانه دستیار',
      group: SettingsGroup.assistant,
      descriptionFa: 'ارائه خلاصه کارهای روز در ابتدای صبح',
      searchTerms: ['خلاصه روز', 'بریفینگ', 'صبحگاهی'],
    ),
    SettingDescriptor(
      key: 'assistant_proactive_enabled',
      type: SettingType.boolean,
      scope: SettingScope.db,
      defaultValue: true,
      labelFa: 'پیشنهادهای پیش‌دستانه',
      group: SettingsGroup.assistant,
      descriptionFa: 'ارائه پیشنهاد استراحت یا فعالیت بر اساس سطح انرژی',
      searchTerms: ['پیشنهاد', 'فعال', 'هوشمند'],
    ),
    SettingDescriptor(
      key: 'gentleness_level',
      type: SettingType.enumeration,
      scope: SettingScope.db,
      defaultValue: 'medium',
      labelFa: 'لحن و نرمی دستیار',
      group: SettingsGroup.assistant,
      allowed: ['gentle', 'medium', 'strict'],
      descriptionFa: 'میزان سخت‌گیری و سبک پیام‌های یادآوری',
      searchTerms: ['لحن', 'سختی', 'سخت‌گیری', 'انعطاف'],
    ),
    SettingDescriptor(
      key: 'daily_capacity_minutes',
      type: SettingType.integer,
      scope: SettingScope.db,
      defaultValue: 480,
      labelFa: 'ظرفیت کار روزانه (دقیقه)',
      group: SettingsGroup.assistant,
      min: 60,
      max: 1440,
      descriptionFa: 'حداکثر دقایق تخصیص داده شده به فعالیت‌های تمرکزی',
      searchTerms: ['ظرفیت', 'توان', 'ساعت کار'],
    ),
    SettingDescriptor(
      key: 'wake_time',
      type: SettingType.time,
      scope: SettingScope.db,
      defaultValue: '06:30',
      labelFa: 'زمان معمول بیداری',
      group: SettingsGroup.assistant,
      descriptionFa: 'آغاز خط زمانی روز در تقویم و برنامه‌ریز',
      searchTerms: ['بیداری', 'صبح', 'طلوع'],
    ),
    SettingDescriptor(
      key: 'sleep_time',
      type: SettingType.time,
      scope: SettingScope.db,
      defaultValue: '23:00',
      labelFa: 'زمان معمول خواب',
      group: SettingsGroup.assistant,
      descriptionFa: 'پایان فعالیت‌های فعال و بسته شدن پرونده روز',
      searchTerms: ['خواب', 'شب', 'استراحت'],
    ),

    // ----------------------------------------------------
    // ۶. داده و پشتیبان (Data & Backup)
    // ----------------------------------------------------
    SettingDescriptor(
      key: 'auto_backup_enabled',
      type: SettingType.boolean,
      scope: SettingScope.db,
      defaultValue: false,
      labelFa: 'پشتیبان‌گیری خودکار',
      group: SettingsGroup.dataBackup,
      descriptionFa: 'ایجاد نسخه پشتیبان دوره‌ای از اطلاعات برنامه',
      searchTerms: ['پشتیبان', 'بکاپ', 'پشتیبان‌گیری'],
    ),
    SettingDescriptor(
      key: 'backup_frequency_days',
      type: SettingType.integer,
      scope: SettingScope.db,
      defaultValue: 7,
      labelFa: 'دورهٔ پشتیبان‌گیری خودکار (روز)',
      group: SettingsGroup.dataBackup,
      min: 1,
      max: 30,
      descriptionFa: 'فاصله زمانی بین هر بار نسخه پشتیبان خودکار',
      searchTerms: ['دوره بکاپ', 'فاصله پشتیبان'],
    ),
    SettingDescriptor(
      key: 'crash_reports_enabled',
      type: SettingType.boolean,
      scope: SettingScope.db,
      defaultValue: true,
      labelFa: 'ثبت گزارش خطاهای سیستم',
      group: SettingsGroup.dataBackup,
      descriptionFa: 'کمک به بهبود پایداری برنامه با ذخیره محلی کرش‌ها',
      searchTerms: ['گزارش خطا', 'کرش', 'لاگ'],
    ),

    // ----------------------------------------------------
    // ۷. امنیت و قفل برنامه (Security)
    // ----------------------------------------------------
    SettingDescriptor(
      key: 'app_lock_enabled',
      type: SettingType.boolean,
      scope: SettingScope.db,
      defaultValue: false,
      labelFa: 'قفل کلی برنامه',
      group: SettingsGroup.security,
      descriptionFa: 'نیاز به ورود رمز یا بیومتریک هنگام باز کردن ریتمو',
      searchTerms: ['قفل', 'امنیت', 'رمز عبور', 'حفاظت'],
    ),
    SettingDescriptor(
      key: 'app_lock_password',
      type: SettingType.text,
      scope: SettingScope.secure,
      defaultValue: '',
      labelFa: 'رمز قفل برنامه',
      group: SettingsGroup.security,
      descriptionFa: 'رمز عددی برای باز کردن برنامه',
      searchTerms: ['پین', 'رمز', 'پسورد'],
    ),
    SettingDescriptor(
      key: 'app_use_device_lock',
      type: SettingType.boolean,
      scope: SettingScope.db,
      defaultValue: false,
      labelFa: 'استفاده از قفل صفحه دستگاه',
      group: SettingsGroup.security,
      descriptionFa: 'استفاده از الگو، پین یا رمز عبور اصلی گوشی',
      searchTerms: ['قفل گوشی', 'پین سیستم', 'الگو'],
    ),
    SettingDescriptor(
      key: 'app_biometric_enabled',
      type: SettingType.boolean,
      scope: SettingScope.db,
      defaultValue: false,
      labelFa: 'ورود با اثر انگشت / چهره',
      group: SettingsGroup.security,
      descriptionFa: 'بازگشایی سریع با حسگرهای بیومتریک گوشی',
      searchTerms: ['اثر انگشت', 'تشخیص چهره', 'بیومتریک'],
    ),
    SettingDescriptor(
      key: 'app_lock_timeout_seconds',
      type: SettingType.integer,
      scope: SettingScope.db,
      defaultValue: 300,
      labelFa: 'مهلت قفل خودکار',
      group: SettingsGroup.security,
      min: -1,
      max: 3600,
      descriptionFa: 'مدت زمان خروج از برنامه تا فعال شدن مجدد قفل (ثانیه)',
      searchTerms: ['زمان قفل', 'تایم اوت قفل', 'قفل خودکار'],
    ),
    SettingDescriptor(
      key: 'cycle_lock_password',
      type: SettingType.text,
      scope: SettingScope.secure,
      defaultValue: '',
      labelFa: 'رمز اختصاصی بخش چرخه زیستی',
      group: SettingsGroup.security,
      descriptionFa: 'رمز مجزا برای ورود به بخش خصوصی چرخه سلامت بانوان',
      searchTerms: ['رمز چرخه', 'قفل چرخه', 'حریم خصوصی'],
    ),
    SettingDescriptor(
      key: 'cycle_biometric_enabled',
      type: SettingType.boolean,
      scope: SettingScope.db,
      defaultValue: false,
      labelFa: 'بیومتریک اختصاصی چرخه',
      group: SettingsGroup.security,
      descriptionFa: 'امکان بازگشایی بخش چرخه با اثر انگشت',
      searchTerms: ['اثر انگشت چرخه', 'بیومتریک چرخه'],
    ),
    // Prompt 063: Task Upgrade Settings
    SettingDescriptor(
      key: 'tasks_completion_sound_enabled',
      type: SettingType.boolean,
      scope: SettingScope.db,
      defaultValue: false,
      labelFa: 'صدای کوتاه هنگام تیک زدن',
      group: SettingsGroup.notifications,
      descriptionFa: 'پخش صدای بومی سیستم هنگام انجام کار یا زیرگام',
      searchTerms: ['صدای تیک', 'صدای تکمیل', 'صدا'],
    ),
    SettingDescriptor(
      key: 'tasks_confirm_delete',
      type: SettingType.boolean,
      scope: SettingScope.db,
      defaultValue: true,
      labelFa: 'پرسیدن قبل از حذف',
      group: SettingsGroup.appearance,
      descriptionFa: 'نمایش دیالوگ تایید قبل از حذف هر کار یا پیوست',
      searchTerms: ['تایید حذف', 'حذف کار', 'هشدار حذف'],
    ),
    SettingDescriptor(
      key: 'daily_planning_nudge_enabled',
      type: SettingType.boolean,
      scope: SettingScope.db,
      defaultValue: false,
      labelFa: 'یادآور «برنامهٔ امروزت را بچین»',
      group: SettingsGroup.notifications,
      descriptionFa: 'ارسال اعلان یادآوری روزانه برای مرور کارهای امروز',
      searchTerms: ['یادآور روزانه', 'برنامه‌ریزی روزانه', 'اعلان'],
    ),
    SettingDescriptor(
      key: 'daily_planning_nudge_time',
      type: SettingType.time,
      scope: SettingScope.db,
      defaultValue: '08:30',
      labelFa: 'ساعت یادآور روزانه',
      group: SettingsGroup.notifications,
      descriptionFa: 'زمان ارسال اعلان یادآوری روزانه',
      searchTerms: ['ساعت یادآور', 'زمان برنامه'],
    ),
  ];

  static SettingDescriptor? find(String key) {
    for (final desc in all) {
      if (desc.key == key) return desc;
    }
    return null;
  }

  static List<SettingDescriptor> userVisibleByGroup(SettingsGroup g) {
    return all.where((d) => d.group == g && d.descriptionFa != null && !d.key.endsWith('_asked') && d.key != 'onboarding_completed').toList(growable: false);
  }

  static List<String> get aiWritableKeys {
    return all.where((d) => d.aiWritable).map((d) => d.key).toList(growable: false);
  }
}
